// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iksvayowsokyqwvnoyau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlrc3ZheW93c29reXF3dm5veWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODUxMzUsImV4cCI6MjA2ODA2MTEzNX0.QH6QB9KGUQPEksBmf4dCxAJBzKZYZxAVIn-377vq8bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});